theme: jekyll-theme-dinky
title: "Static Site Generator"
## Maiah Frias
## 9-Brebeuf
## <dt>Fave Music Artists</dt>
#### <dd>Luke Chiang</dd>
#### <dd>The Ridleys</dd>
#### </dd>Seventeen</dd>

